name: Prevent push to master

on:
  push:
    branches:
      - master

jobs:
  prevent-push:
    runs-on: ubuntu-latest

    steps:
    - name: Get branch information
      run: echo ::set-output name=branch_name::$(echo ${GITHUB_REF} | awk -F/ '{print $3}')

    - name: Check if the branch is master
      if: steps.get_branch_information.outputs.branch_name == 'master'
      run: |
        echo "Pushing to master branch is not allowed"
        exit 1
